CREATE DATABASE COMPETICION;
USE COMPETICION;

CREATE TABLE IF NOT EXISTS EQUIPOS(
    NOMBRE VARCHAR(50) NOT NULL PRIMARY KEY,
    SELECCIONADOR VARCHAR(50) NOT NULL,
    EDICIONES VARCHAR(50) NOT NULL,
    LUGAR VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS JUGADORES(
    NOMBRE VARCHAR(50) NOT NULL PRIMARY KEY,
    EQUIPO VARCHAR(50) NOT NULL,
    EDICIONES VARCHAR(50) NOT NULL,
    COMPETICIONES_GANADAS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ANFITRION(
    PAIS VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ESDEVENIMIENTOS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    CIUDAD VARCHAR(50) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    CAMPEONES VARCHAR(50) NOT NULL
);
